//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.ProduceStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produce
    {
        public int ProduceId { get; set; }
        public string ProduceName { get; set; }
        public string ProduceType { get; set; }
        public string Season { get; set; }
        public double Price { get; set; }
        public int Stock { get; set; }
        public string PluralName { get; set; }
    }
}
