//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.ProduceStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int RuleId { get; set; }
        public string RegularExpression { get; set; }
        public int RegExGroup { get; set; }
        public string Query { get; set; }
        public string RuleStatus { get; set; }
        public string LastUpdateUser { get; set; }
    }
}
